/* tslint:disable */
/* eslint-disable */
/**
 * Code Connect API
 * Code Connectで利用するAPIの定義 # Feature - theme   - テーマをサーバーから取得するAPI - code   - ユーザーが作成したコードをサーバーに送信する機能  More Info =>  Notion 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Theme,
} from '../models';
import {
    ThemeFromJSON,
    ThemeToJSON,
} from '../models';

/**
 * 
 */
export class ThemeApi extends runtime.BaseAPI {

    /**
     * APIサーバーからテーマデータの一覧を受け取るためのAPI
     */
    async apiThemeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Theme>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/theme`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThemeFromJSON(jsonValue));
    }

    /**
     * APIサーバーからテーマデータの一覧を受け取るためのAPI
     */
    async apiThemeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Theme> {
        const response = await this.apiThemeGetRaw(initOverrides);
        return await response.value();
    }

}
