"use client";

import "./globals.css";
import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import CodeDataProvider from "@/providers/code_data_provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <CodeDataProvider
          data={{
            id: -1,
            themeId: -1,
            code: "",
            timeStamp: "",
          }}
        >
          <ChakraProvider>{children}</ChakraProvider>
        </CodeDataProvider>
      </body>
    </html>
  );
}
