/* tslint:disable */
/* eslint-disable */
/**
 * Code Connect API
 * Code Connectで利用するAPIの定義 # Feature - theme   - テーマをサーバーから取得するAPI - code   - ユーザーが作成したコードをサーバーに送信する機能  More Info =>  Notion 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Theme } from './Theme';
import {
    ThemeFromJSON,
    ThemeFromJSONTyped,
    ThemeToJSON,
} from './Theme';

/**
 * 
 * @export
 * @interface ApiThemeGet200Response
 */
export interface ApiThemeGet200Response {
    /**
     * 
     * @type {Array<Theme>}
     * @memberof ApiThemeGet200Response
     */
    themes?: Array<Theme>;
}

/**
 * Check if a given object implements the ApiThemeGet200Response interface.
 */
export function instanceOfApiThemeGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiThemeGet200ResponseFromJSON(json: any): ApiThemeGet200Response {
    return ApiThemeGet200ResponseFromJSONTyped(json, false);
}

export function ApiThemeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiThemeGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'themes': !exists(json, 'themes') ? undefined : ((json['themes'] as Array<any>).map(ThemeFromJSON)),
    };
}

export function ApiThemeGet200ResponseToJSON(value?: ApiThemeGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'themes': value.themes === undefined ? undefined : ((value.themes as Array<any>).map(ThemeToJSON)),
    };
}

