/* tslint:disable */
/* eslint-disable */
/**
 * Code Connect API
 * Code Connectで利用するAPIの定義 # Feature - theme   - テーマをサーバーから取得するAPI - code   - ユーザーが作成したコードをサーバーに送信する機能  More Info =>  Notion 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostBody
 */
export interface PostBody {
    /**
     * 
     * @type {number}
     * @memberof PostBody
     */
    themeId?: number;
    /**
     * 
     * @type {string}
     * @memberof PostBody
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof PostBody
     */
    code?: string;
}

/**
 * Check if a given object implements the PostBody interface.
 */
export function instanceOfPostBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostBodyFromJSON(json: any): PostBody {
    return PostBodyFromJSONTyped(json, false);
}

export function PostBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'themeId': !exists(json, 'themeId') ? undefined : json['themeId'],
        'language': !exists(json, 'language') ? undefined : json['language'],
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function PostBodyToJSON(value?: PostBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'themeId': value.themeId,
        'language': value.language,
        'code': value.code,
    };
}

